export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
  //Header
  'Language': 'Language',
  'Login': 'Login',
  'Register': 'Register',
  'ABOUT US': 'ABOUT US',
  'WHY DOMINIUM': 'WHY DOMINIUM',
  'ROAD MAP': 'ROAD MAP',
  'TOKEN DETAILS': 'TOKEN DETAILS',
  'Pitch Deck': 'Pitch Deck',
  'White Paper': 'White Paper',
  'FAQ': 'FAQ',
  'AIR DROP': 'AIR DROP',
  'TEAM': 'TEAM',
  'Lorem Ipsum is simply dummy text of': 'Lorem Ipsum is simply dummy text of',
  'the printing and typesetting industry.' : 'the printing and typesetting industry.',
  'Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.': 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s,when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
  'JOIN OUR TELEGRAM CHANNEL NOW!': 'JOIN OUR TELEGRAM CHANNEL NOW!',
  'BUY DOM TOKENS NOW!': 'BUY DOM TOKENS NOW!',
  'Follow Us': 'Follow Us',

  // body.........
  // section 1

  'OUR PARTNERS': 'OUR PARTNERS',
  //section2
  'Videos Title': 'Videos Title',
  'SURFACE PRO (2018)': 'SURFACE PRO (2018)',
  'Introducing Microsoft Surface Hub 2': 'Introducing Microsoft Surface Hub 2',
  'iPad Pro after one week: Can it replace your laptop?': 'iPad Pro after one week: Can it replace your laptop?',
  // section4
  'Who We Are': 'Who We Are',
  'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently withdesktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.': 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
  'Read More': 'Read More',
  // section5
  'What We Do': 'What We Do',
  //section6
  'How We do it': 'How We do it',
  'Lorem Ipsum is simply dummy text of the printing and typesetting industry.': 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
  'Regulated': 'Regulated',
  'when an unknown printer took a galley of type and scrambled it to make a type specimen book.': 'when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
  'It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.': 'It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
  'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC.': 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC.',
  'Multi-Lingual': 'Multi-Lingual',
  'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form,': 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form,',
  'Secure': 'Secure',
  'Transparent': 'Transparent',
  'Multi-Currency': 'Multi-Currency',
  'by injected humour, or randomised words which do not look even slightly believable.': 'by injected humour, or randomised words which do not look even slightly believable.',
  'Property Funding': 'Property Funding',
  'Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.': 'Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.',
  'Project Finance': 'Project Finance',
  'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested.': 'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested.',
  'Property Sales': 'Property Sales',
  'Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).': 'Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).',
  'Property Rentals': 'Property Rentals',
  'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour,': 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour,',
  'Property Management': 'Property Management',
  'It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.': 'It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
  'Self-Sufficient': 'Self-Sufficient',
  'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.': 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
  //section7
  'The Problem': 'The Problem',
  'The Solution': 'The Solution',
  // roadmap
  'Roadmap': 'Roadmap',
  '2012 Initial idea': '2012 Initial idea',
  'to develop a blockchain platform for property funding': 'to develop a blockchain platform for property funding',
  'Blockchain technology reaches maturity required to launch a regulated platform for property financing.': 'Blockchain technology reaches maturity required to launch a regulated platform for property financing.',
  'Financial Holding Company incorporated in the Netherlands for first Max Property Group property funds.': 'Financial Holding Company incorporated in the Netherlands for first Max Property Group property funds.',
  'Founders money used to prove financial model by buying, renovating and renting out apartments in Rotterdam.': 'Founders money used to prove financial model by buying, renovating and renting out apartments in Rotterdam.',
  'Max Property Group website developed and translated into three languages (English, Dutch and German).': 'Max Property Group website developed and translated into three languages (English, Dutch and German).',
  'Regulatory compliant prospectus for first Dutch property fund completed.': 'Regulatory compliant prospectus for first Dutch property fund completed.',
  'Max Property Group Netherland goes live and is fully subscribed within the set time frame.': 'Max Property Group Netherland goes live and is fully subscribed within the set time frame.',
  ' Regulatory compliant documentation for Max Property Group Germany and United Kingdom completed.': ' Regulatory compliant documentation for Max Property Group Germany and United Kingdom completed.',
  'Max Property Group Germany and United Kingdom launched (currently raising funds).': 'Max Property Group Germany and United Kingdom launched (currently raising funds).',
  'Dominium team appointed, technology selected, and development team contracted.': 'Dominium team appointed, technology selected, and development team contracted.',
  'Platform development started, website designed, and referral program created.': 'Platform development started, website designed, and referral program created.',
  'Private funding round closed to pay for initial platform development.': 'Private funding round closed to pay for initial platform development.',
  'Initial Financial Holding Company name changed to Dominium B.V.': 'Initial Financial Holding Company name changed to Dominium B.V.',
  'Finalise English version of Platform and initiate pre-ITO and ITO rounds.': 'Finalise English version of Platform and initiate pre-ITO and ITO rounds.',
  'Purchase property in NL, DE and UK, migrate all MPG assets to platform, finalise beta-testing of all functionalities.': 'Purchase property in NL, DE and UK, migrate all MPG assets to platform, finalise beta-testing of all functionalities.',
  //section8
  'Token Sale Details': 'Token Sale Details',
  'Total Token Supply': 'Total Token Supply',
  'Number of tokens for sale': 'Number of tokens for sale',
  'Seed round': 'Seed round',
  '(Sold out)': '(Sold out)',
  'Pre-ITO / Private Sale - €0.05 per DOM (From 15/08/2018 12:00 CET to 31/08/2018 12:00 CET)': 'Pre-ITO / Private Sale - €0.05 per DOM (From 15/08/2018 12:00 CET to 31/08/2018 12:00 CET)',
  //section9
  'Token Values': 'Token Values',
  'DOM tokens are used to pay for all activities on the platform, such as:': 'DOM tokens are used to pay for all activities on the platform, such as:',
  'Creation of Assets': 'Creation of Assets',
  'Trading of Assets': 'Trading of Assets',
  'Creation of support tickets': '',
  'Voting for charities': 'Voting for charities',
  'Listing a property for sale': 'Listing a property for sale',
  'Listing a property for rent': 'Listing a property for rent',
  'Registering a rental agreement': 'Registering a rental agreement',
  'Registering a purchase agreement': 'Registering a purchase agreement',
  'Fees charged on DOMINIUM are charged in EURO, but can only be paid in DOM tokens:': 'Fees charged on DOMINIUM are charged in EURO, but can only be paid in DOM tokens:',
  '€0,25 for each support ticket creation': '€0,25 for each support ticket creation',
  '€0,50 to vote for a charity': '€0,50 to vote for a charity',
  '€1,00 to buy an Asset': '€1,00 to buy an Asset',
  '€1,00 to sell an Asset': '€1,00 to sell an Asset',
  '€1,00 to list a property': '€1,00 to list a property',
  '€2,50 to register a rental agreement': '€2,50 to register a rental agreement',
  '€5,00 to register a purchase agreement': '€5,00 to register a purchase agreement',
  '€500 to create a non-regulated Asset (exempt)': '€500 to create a non-regulated Asset (exempt)',
  '€2,500 to create a regulated Asset': '€2,500 to create a regulated Asset',
  //section10
  'Token Burn Program': 'Token Burn Program',
  'All DOM tokens collected on DOMINIUM and acquired via the buy-back program will be collected in a multi-signatory account, of which the company supervisor, Confidon, will be a signatory. These tokens will therefore be taken out of circulation upon deposit in the account and will be burned (destroyed) every year, or as required. Token burns will be audited and publicly announced.': 'All DOM tokens collected on DOMINIUM and acquired via the buy-back program will be collected in a multi-signatory account, of which the company supervisor, Confidon, will be a signatory. These tokens will therefore be taken out of circulation upon deposit in the account and will be burned (destroyed) every year, or as required. Token burns will be audited and publicly announced.',
  'This makes the DOM token one of the few tokens with a diminishing supply!!!': 'This makes the DOM token one of the few tokens with a diminishing supply!!!',
  //section11
  'Buy-Back Program': 'Buy-Back Program',
  'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.': 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
  'It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.': 'It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
  //section12
  'Air Drop': 'Air Drop',
  'REGISTER an account as an individual and receive 25 DOM tokens.': 'REGISTER an account as an individual and receive 25 DOM tokens.',
  'INTRODUCE a friend and you both receive 25 DOM!': 'INTRODUCE a friend and you both receive 25 DOM!',
  'REGISTER an account as a company and receive 100 DOM tokens.': 'REGISTER an account as a company and receive 100 DOM tokens.',
  'INTRODUCE a company and both of you receive 100 DOM!': 'INTRODUCE a company and both of you receive 100 DOM!',
  'A total of 100,000,000 DOM tokens (10%) will be given away during the Air Drop and Referral Program.': 'A total of 100,000,000 DOM tokens (10%) will be given away during the Air Drop and Referral Program.',
  'Air Drop!': 'Air Drop!',
  //block-wrap
  '': '',


};
